<?php
return array(
	array(
		'storage_id'		=> 1,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '1',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '38.50',
		'size_code'			=> '1',
	),
	array(
		'storage_id'		=> 1,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '2',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '69.50',
		'size_code'			=> '2',
	),
	array(
		'storage_id'		=> 1,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '4',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '118.50',
		'size_code'			=> '4',
	),
	array(
		'storage_id'		=> 1,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '3',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '156.50',
		'size_code'			=> '6',
	),
	array(
		'storage_id'		=> 1,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '4',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '190.50',
		'size_code'			=> '8',
	),
	array(
		'storage_id'		=> 1,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '5',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '215.00',
		'size_code'			=> '10',
	),
	array(
		'storage_id'		=> 2,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '1',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '38.50',
		'size_code'			=> '1',
	),
	array(
		'storage_id'		=> 2,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '2',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '69.50',
		'size_code'			=> '2',
	),
	array(
		'storage_id'		=> 2,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '4',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '118.50',
		'size_code'			=> '4',
	),
	array(
		'storage_id'		=> 2,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '3',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '156.50',
		'size_code'			=> '6',
		'note'				=> 'Nichts besonderes aber hier stehts',
	),
	array(
		'storage_id'		=> 2,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '4',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '190.50',
		'size_code'			=> '8',
	),
	array(
		'storage_id'		=> 2,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '5',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '215.00',
		'size_code'			=> '10',
	),
	array(
		'storage_id'		=> 2,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '3',
		'room_width'		=> '3',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '38.50',
		'size_code'			=> '1',
	),
	array(
		'storage_id'		=> 2,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '3',
		'room_width'		=> '4',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '69.50',
		'size_code'			=> '2',
	),
	array(
		'storage_id'		=> 2,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '3',
		'room_width'		=> '5',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '118.50',
		'size_code'			=> '4',
	),
	array(
		'storage_id'		=> 2,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '3',
		'room_width'		=> '6',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '156.50',
		'size_code'			=> '6',
	),
	array(
		'storage_id'		=> 2,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '3',
		'room_width'		=> '7',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '190.50',
		'size_code'			=> '8',
	),
	array(
		'storage_id'		=> 2,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '4',
		'room_width'		=> '8',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '215.00',
		'size_code'			=> '10',
	),
	array(
		'storage_id'		=> 3,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '1',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '37.50',
		'size_code'			=> '1',
	),
	array(
		'storage_id'		=> 3,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '2',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '66.50',
		'size_code'			=> '2',
	),
	array(
		'storage_id'		=> 3,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '4',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '111.50',
		'size_code'			=> '4',
	),
	array(
		'storage_id'		=> 3,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '3',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '148.50',
		'size_code'			=> '6',
	),
	array(
		'storage_id'		=> 3,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '4',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '178.50',
		'size_code'			=> '8',
	),
	array(
		'storage_id'		=> 3,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '5',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '202.00',
		'size_code'			=> '10',
	),
	array(
		'storage_id'		=> 6,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '1',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '37.50',
		'size_code'			=> '1',
	),
	array(
		'storage_id'		=> 6,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '2',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '66.50',
		'size_code'			=> '2',
	),
	array(
		'storage_id'		=> 6,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '4',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '111.50',
		'size_code'			=> '4',
	),
	array(
		'storage_id'		=> 6,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '3',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '148.50',
		'size_code'			=> '6',
	),
	array(
		'storage_id'		=> 6,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '4',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '178.50',
		'size_code'			=> '8',
	),
	array(
		'storage_id'		=> 6,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '5',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '202.00',
		'size_code'			=> '10',
	),
	array(
		'storage_id'		=> 7,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '1',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '38.50',
		'size_code'			=> '1',
	),
	array(
		'storage_id'		=> 7,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '2',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '69.50',
		'size_code'			=> '2',
	),
	array(
		'storage_id'		=> 7,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '4',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '118.50',
		'size_code'			=> '4',
	),
	array(
		'storage_id'		=> 7,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '3',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '156.50',
		'size_code'			=> '6',
	),
	array(
		'storage_id'		=> 7,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '4',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '190.50',
		'size_code'			=> '8',
	),
	array(
		'storage_id'		=> 7,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '5',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '215.00',
		'size_code'			=> '10',
	),
	array(
		'storage_id'		=> 8,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '1',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '38.50',
		'size_code'			=> '1',
	),
	array(
		'storage_id'		=> 8,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '2',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '69.50',
		'size_code'			=> '2',
	),
	array(
		'storage_id'		=> 8,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '1',
		'room_width'		=> '4',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '118.50',
		'size_code'			=> '4',
	),
	array(
		'storage_id'		=> 8,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '3',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '156.50',
		'size_code'			=> '6',
	),
	array(
		'storage_id'		=> 8,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '4',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '190.50',
		'size_code'			=> '8',
	),
	array(
		'storage_id'		=> 8,
		'date_created'		=> date('Y-m-d'),
		'room_height'		=> '2.4',
		'room_length'		=> '2',
		'room_width'		=> '5',
		'unit_type'    		=> '1',
		'unit_number'		=> NULL,
		'rate_period'		=> 2, // 1=week, 2=4weeks, 3=monthly, 0=daily
		'unit_rate'			=> '215.00',
		'size_code'			=> '10',
	),
);
