<?php

return array(
	'site1' => array(
		'user_id'		=> 3,
		'name'          => 'Langenzersdorf',
		'country'       => 'AT',
		'address'       => 'Plantagenstraße 4',
		'zipcode'       => '2103',
		'city'          => 'Langenzersdorf',
		'no_latitude'	=> '48.289117',
		'no_longitude'  => '16.367964',
	),
	'site2' => array(
		'user_id'		=> 3,
		'name'          => 'Heiligenstadt',
		'country'       => 'AT',
		'address'       => 'Heiligenstädterstrasse 62',
		'zipcode'       => '1190',
		'city'          => 'Wien',
		'no_latitude'	=> '48.242110',
		'no_longitude'  => '16.361418',
	),
	'site3' => array(
		'user_id'		=> 3,
		'name'          => 'Floridsdorf',
		'country'       => 'AT',
		'address'       => 'Katsushikastraße 4',
		'zipcode'       => '1210',
		'city'          => 'Wien',
		'no_latitude'	=> '48.264915',
		'no_longitude'  => '16.399218',
	),
	'site4' => array(
		'user_id'		=> 3,
		'name'          => 'Forstenried',
		'country'       => 'DE',
		'address'       => 'Drygalski-Allee',
		'zipcode'       => '81477',
		'city'          => 'München',
		'no_latitude'	=> '48.088650',
		'no_longitude'  => '11.503039',
	),
	'site5' => array(
		'user_id'		=> 3,
		'name'          => 'Giesing',
		'country'       => 'DE',
		'address'       => 'Chiemgaustrasse 107',
		'zipcode'       => '81549',
		'city'          => 'München',
		'no_latitude'	=> '48.107031',
		'no_longitude'  => '11.596898',
	),
	'site6' => array(
		'user_id'		=> 3,
		'name'          => 'Magareten',
		'country'       => 'AT',
		'address'       => 'Gaudenzdorfer Gürtel 51-59',
		'zipcode'       => '1120',
		'city'          => 'Wien',
		'no_latitude'	=> '48.187261',
		'no_longitude'  => '16.342320',
	),
	'site7' => array(
		'user_id'		=> 3,
		'name'          => 'Hirschstetten',
		'country'       => 'AT',
		'address'       => 'Franz-Fellner-Gasse 5',
		'zipcode'       => '1220',
		'city'          => 'Wien',
		'no_latitude'	=> '48.236595',
		'no_longitude'  => '16.458939',
	),
	'site8' => array(
		'user_id'		=> 3,
		'name'          => 'Favoriten',
		'country'       => 'AT',
		'address'       => 'Grenzackerstraße 4',
		'zipcode'       => '1100',
		'city'          => 'Wien',
		'no_latitude'	=> '48.163021',
		'no_longitude'  => '16.379081',
	),
	'site9' => array(
		'user_id'		=> 3,
		'name'          => 'Liesing',
		'country'       => 'AT',
		'address'       => 'Breitenfurterstraße 247a',
		'zipcode'       => '1230',
		'city'          => 'Wien',
		'no_latitude'	=> '48.152167',
		'no_longitude'  => '16.302148',
	),
	'site10' => array(
		'user_id'		=> 3,
		'name'          => 'Hietzing',
		'country'       => 'AT',
		'address'       => 'Hietzinger Kai 79',
		'zipcode'       => '1130',
		'city'          => 'Wien',
		'no_latitude'	=> '48.189927',
		'no_longitude'  => '16.292429',
	),
	'site11' => array(
		'user_id'		=> 3,
		'name'          => 'Hernals',
		'country'       => 'AT',
		'address'       => 'Wattgasse 40-44',
		'zipcode'       => '1160',
		'city'          => 'Wien',
		'no_latitude'	=> '48.217044',
		'no_longitude'  => '16.319916',
	),
	'site12' => array(
		'user_id'		=> 3,
		'name'          => 'Rudolfsheim',
		'country'       => 'AT',
		'address'       => 'Mariahilfer Straße 198',
		'zipcode'       => '1150',
		'city'          => 'Wien',
		'no_latitude'	=> '48.191027',
		'no_longitude'  => '16.325592',
	),
);

