<?php

return array(
  array('username' => 'admin','password' => md5('admin'),'email' => 'admin@localhost','role' => '1','position' => '1','prename' => 'Philipp','name' => 'Frenzel','phone' => '+43 699 19089393','mobile' => '+43 699 19089393','fax' => '','messanger' => 'philipp_frenzel','parent_user_id' => NULL,'backup_user_id' => NULL,'time_create' => NULL,'time_update' => NULL,'time_login' => NULL,'date_entry' => '2011-04-01','date_exit' => NULL,'no_employee' => NULL),
  array('username' => 'user','password' => md5('user'),'email' => 'philipp@frenzel.net','role' => '3','position' => '2','prename' => 'Philipp','name' => 'Frenzel','phone' => '+(43) 1 36 71 0551','mobile' => '+(43) 699 19 08 9393','fax' => '+(43) 1 36 71 0559','messanger' => '','parent_user_id' => NULL,'backup_user_id' => NULL,'time_create' => NULL,'time_update' => NULL,'time_login' => NULL,'date_entry' => '2011-04-01','date_exit' => NULL,'no_employee' => null),
  array('username' => 'myplace_selfstorage','password' => md5('myplaceisyourplace'),'email' => 'philipp.frenzel@myplace.eu','role' => '3','position' => '0','prename' => 'MyPlace','name' => 'Selfstorage','phone' => '+(43) 1 36 71 0551','mobile' => '+(43) 699 19 08 9393','fax' => '+(43) 1 36 71 0559','messanger' => '','parent_user_id' => NULL,'backup_user_id' => NULL,'time_create' => NULL,'time_update' => NULL,'time_login' => NULL,'date_entry' => date('Y-m-d'),'date_exit' => NULL,'no_employee' => null),
  array('username' => 'dein_depot','password' => md5('dein_depot'),'email' => 'philipp@frenzel.net','role' => '3','position' => '0','prename' => 'Dein','name' => 'Depot','phone' => '+(43) ','mobile' => '+(43) 699 11 96 6495','fax' => '+(43) ','messanger' => '','parent_user_id' => NULL,'backup_user_id' => NULL,'time_create' => NULL,'time_update' => NULL,'time_login' => NULL,'date_entry' => date('Y-m-d'),'date_exit' => NULL,'no_employee' => null),
  array('username' => 'lagerbox','password' => md5('lagerbox'),'email' => 'info@lagerbox.at','role' => '3','position' => '0','prename' => 'Lagerbox Holding','name' => 'GmbH & Co. KG','phone' => '+(43) ','mobile' => '+(43) 699 11 96 6495','fax' => '+(43) ','messanger' => '','parent_user_id' => NULL,'backup_user_id' => NULL,'time_create' => NULL,'time_update' => NULL,'time_login' => NULL,'date_entry' => date('Y-m-d'),'date_exit' => NULL,'no_employee' => null),
  array('username' => 'maxmuster','password' => md5('maxmuster'),'email' => 'max@checkstorage.de','role' => '1','position' => '0','prename' => 'Max','name' => 'Muster','phone' => '+(43) ','mobile' => '+(43) 699 11 96 6495','fax' => '+(43) ','messanger' => '','parent_user_id' => NULL,'backup_user_id' => NULL,'time_create' => NULL,'time_update' => NULL,'time_login' => NULL,'date_entry' => date('Y-m-d'),'date_exit' => NULL,'no_employee' => null),
  array('username' => 'danielamueller','password' => md5('danielamueller'),'email' => 'daniela@checkstorage.de','role' => '1','position' => '0','prename' => 'Daniela','name' => 'Müller','phone' => '+(43) ','mobile' => '+(43) 699 11 96 6495','fax' => '+(43) ','messanger' => '','parent_user_id' => NULL,'backup_user_id' => NULL,'time_create' => NULL,'time_update' => NULL,'time_login' => NULL,'date_entry' => date('Y-m-d'),'date_exit' => NULL,'no_employee' => null),
  array('username' => 'shurgard','password' => md5('shurgard'),'email' => 'info@shurgard.fr','role' => '3','position' => '0','prename' => 'Shurgard','name' => 'Self-Storage','phone' => '+(43) ','mobile' => '+(43) 699 11 96 6495','fax' => '+(43) ','messanger' => '','parent_user_id' => NULL,'backup_user_id' => NULL,'time_create' => NULL,'time_update' => NULL,'time_login' => NULL,'date_entry' => date('Y-m-d'),'date_exit' => NULL,'no_employee' => null),  
  array('username' => 'zebrabox','password' => md5('zebrabox'),'email' => 'kontakt@zebrabox.ch','role' => '3','position' => '0','prename' => 'Zebrabox','name' => 'Self Storage AG','phone' => '+(43) ','mobile' => '+(43) 699 11 96 6495','fax' => '+(43) ','messanger' => '','parent_user_id' => NULL,'backup_user_id' => NULL,'time_create' => NULL,'time_update' => NULL,'time_login' => NULL,'date_entry' => date('Y-m-d'),'date_exit' => NULL,'no_employee' => null),  
  array('username' => 'diskont_depot','password' => md5('diskont_depot'),'email' => 'diskont_depot@checkstorage.at','role' => '3','position' => '0','prename' => 'DISKONT','name' => 'Vermietungs- und VeranstaltungsgmbH','phone' => '+(43) ','mobile' => '+(43) 699 11 96 6495','fax' => '+(43) ','messanger' => '','parent_user_id' => NULL,'backup_user_id' => NULL,'time_create' => NULL,'time_update' => NULL,'time_login' => NULL,'date_entry' => date('Y-m-d'),'date_exit' => NULL,'no_employee' => null),  
);
