<?php

return array(
	array(
		'user_id'		=> 6,
		'country'       => 'AT',
		'address'       => 'Hohlweggasse 7',
		'zipcode'       => '1030',
		'city'          => 'Wien',
		'no_latitude'	=> '48.289117',
		'no_longitude'  => '16.367964',
		'double_sqm'	=> '1.00',
		'date_start'	=> date('Y-m-d',strtotime('today +2 weeks')),
		'date_created'	=> date('Y-m-d'),
	),
	array(
		'user_id'		=> 7,
		'country'       => 'AT',
		'address'       => 'Hohlweggasse 7',
		'zipcode'       => '1030',
		'city'          => 'Wien',
		'no_latitude'	=> '48.289117',
		'no_longitude'  => '16.367964',
		'double_sqm'	=> '1.00',
		'date_start'	=> date('Y-m-d',strtotime('today +2 weeks')),
		'date_created'	=> date('Y-m-d'),
	),
	array(
		'user_id'		=> 6,
		'country'       => 'DE',
		'address'       => 'Hauptstrasse 12',
		'zipcode'       => '11304',
		'city'          => 'Berlin',
		'no_latitude'	=> '48.289117',
		'no_longitude'  => '16.367964',
		'double_sqm'	=> '1.00',
		'date_start'	=> date('Y-m-d',strtotime('today +2 weeks')),
		'date_created'	=> date('Y-m-d'),
	),
	array(
		'user_id'		=> 7,
		'country'       => 'DE',
		'address'       => 'Hauptstrasse 12',
		'zipcode'       => '11030',
		'city'          => 'Berlin',
		'no_latitude'	=> '48.289117',
		'no_longitude'  => '16.367964',
		'double_sqm'	=> '13.00',
		'date_start'	=> date('Y-m-d',strtotime('today +2 weeks')),
		'date_created'	=> date('Y-m-d'),
	),
	array(
		'user_id'		=> 6,
		'country'       => 'AT',
		'address'       => 'Hohlweggasse 7',
		'zipcode'       => '1030',
		'city'          => 'Wien',
		'no_latitude'	=> '48.289117',
		'no_longitude'  => '16.367964',
		'double_sqm'	=> '15.00',
		'date_start'	=> date('Y-m-d',strtotime('today +4 weeks')),
		'date_created'	=> date('Y-m-d'),
	),
	array(
		'user_id'		=> 7,
		'country'       => 'AT',
		'address'       => 'Hohlweggasse 7',
		'zipcode'       => '1030',
		'city'          => 'Wien',
		'no_latitude'	=> '48.289117',
		'no_longitude'  => '16.367964',
		'double_sqm'	=> '1.00',
		'date_start'	=> date('Y-m-d',strtotime('today +4 weeks')),
		'date_created'	=> date('Y-m-d'),
	),
	array(
		'user_id'		=> 6,
		'country'       => 'DE',
		'address'       => 'Hauptstrasse 12',
		'zipcode'       => '70469',
		'city'          => 'Stuttgart',
		'no_latitude'	=> '48.289117',
		'no_longitude'  => '16.367964',
		'double_sqm'	=> '25.00',
		'date_start'	=> date('Y-m-d',strtotime('today +4 weeks')),
		'date_created'	=> date('Y-m-d'),
	),
	array(
		'user_id'		=> 7,
		'country'       => 'DE',
		'address'       => 'Hauptstrasse 12',
		'zipcode'       => '70152',
		'city'          => 'Stuttgart',
		'no_latitude'	=> '48.289117',
		'no_longitude'  => '16.367964',
		'double_sqm'	=> '13.00',
		'date_start'	=> date('Y-m-d',strtotime('today +4 weeks')),
		'date_created'	=> date('Y-m-d'),
	),
	array(
		'user_id'		=> 6,
		'country'       => 'AT',
		'address'       => 'Hohlweggasse 7',
		'zipcode'       => '1030',
		'city'          => 'Wien',
		'no_latitude'	=> '48.289117',
		'no_longitude'  => '16.367964',
		'double_sqm'	=> '12.00',
		'date_start'	=> date('Y-m-d',strtotime('today +6 weeks')),
		'date_created'	=> date('Y-m-d'),
	),
	array(
		'user_id'		=> 7,
		'country'       => 'AT',
		'address'       => 'Hohlweggasse 7',
		'zipcode'       => '1030',
		'city'          => 'Wien',
		'no_latitude'	=> '48.289117',
		'no_longitude'  => '16.367964',
		'double_sqm'	=> '7.00',
		'date_start'	=> date('Y-m-d',strtotime('today +6 weeks')),
		'date_created'	=> date('Y-m-d'),
	),
);

