<?php

return array(
	'site1' => array(
		'user_id'		=> 3,
		'name'          => 'Langenzersdorf',		
		'country'       => 'AT',
		'address'       => 'Plantagenstraße 4',
		'zipcode'       => '2103',
		'city'          => 'Langenzersdorf',
		'no_latitude'	=> '48.289117',
		'no_longitude'  => '16.367964',
	),
	'site2' => array(
		'user_id'		=> 3,
		'name'          => 'Heiligenstadt',		
		'country'       => 'AT',
		'address'       => 'Heiligenstädterstrasse 62',
		'zipcode'       => '1190',
		'city'          => 'Wien',
		'no_latitude'	=> '48.242110',
		'no_longitude'  => '16.361418',
	),
	'site3' => array(
		'user_id'		=> 3,
		'name'          => 'Floridsdorf',	
		'country'       => 'AT',
		'address'       => 'Katsushikastraße 4',
		'zipcode'       => '1210',
		'city'          => 'Wien',
		'no_latitude'	=> '48.264915',
		'no_longitude'  => '16.399218',
	),
	'site4' => array(
		'user_id'		=> 3,
		'name'          => 'Forstenried',		
		'country'       => 'DE',
		'address'       => 'Drygalski-Allee',
		'zipcode'       => '81477',
		'city'          => 'München',
		'no_latitude'	=> '48.088650',
		'no_longitude'  => '11.503039',
	),
	'site5' => array(
		'user_id'		=> 3,
		'name'          => 'Giesing',		
		'country'       => 'DE',
		'address'       => 'Chiemgaustrasse 107',
		'zipcode'       => '81549',
		'city'          => 'München',
		'no_latitude'	=> '48.107031',
		'no_longitude'  => '11.596898',
	),
	'site6' => array(
		'user_id'		=> 3,
		'name'          => 'Magareten',		
		'country'       => 'AT',
		'address'       => 'Gaudenzdorfer Gürtel 51-59',
		'zipcode'       => '1120',
		'city'          => 'Wien',
		'no_latitude'	=> '48.187261',
		'no_longitude'  => '16.342320',
	),
	'site7' => array(
		'user_id'		=> 3,
		'name'          => 'Hirschstetten',		
		'country'       => 'AT',
		'address'       => 'Franz-Fellner-Gasse 5',
		'zipcode'       => '1220',
		'city'          => 'Wien',
		'no_latitude'	=> '48.236595',
		'no_longitude'  => '16.458939',
	),
	'site8' => array(
		'user_id'		=> 3,
		'name'          => 'Favoriten',		
		'country'       => 'AT',
		'address'       => 'Grenzackerstraße 4',
		'zipcode'       => '1100',
		'city'          => 'Wien',
		'no_latitude'	=> '48.163021',
		'no_longitude'  => '16.379081',
	),
	'site9' => array(
		'user_id'		=> 3,
		'name'          => 'Liesing',		
		'country'       => 'AT',
		'address'       => 'Breitenfurterstraße 247a',
		'zipcode'       => '1230',
		'city'          => 'Wien',
		'no_latitude'	=> '48.152167',
		'no_longitude'  => '16.302148',
	),
	'site10' => array(
		'user_id'		=> 3,
		'name'          => 'Hietzing',		
		'country'       => 'AT',
		'address'       => 'Hietzinger Kai 79',
		'zipcode'       => '1130',
		'city'          => 'Wien',
		'no_latitude'	=> '48.189927',
		'no_longitude'  => '16.292429',
	),
	'site11' => array(
		'user_id'		=> 3,
		'name'          => 'Hernals',		
		'country'       => 'AT',
		'address'       => 'Wattgasse 40-44',
		'zipcode'       => '1160',
		'city'          => 'Wien',
		'no_latitude'	=> '48.217044',
		'no_longitude'  => '16.319916',
	),
	'site12' => array(
		'user_id'		=> 3,
		'name'          => 'Rudolfsheim',		
		'country'       => 'AT',
		'address'       => 'Mariahilfer Straße 198',
		'zipcode'       => '1150',
		'city'          => 'Wien',
		'no_latitude'	=> '48.191027',
		'no_longitude'  => '16.325592',
	),
	array(
		'user_id' => '3',
		'name' => 'Graz',	
		'country' => 'AT',
		'address' => 'Starhemberggasse 4',
		'zipcode' => '8020',
		'city' => 'Graz',
		'no_latitude'	=> '47.075107',
		'no_longitude'  => '15.411952',
	),
	array(
		'user_id' => '3',
		'name' => 'Linz',	
		'country' => 'AT',
		'address' => 'Unionstraße 73',
		'zipcode' => '4020',
		'city' => 'Linz',
		'no_latitude'	=> '48.282620',
		'no_longitude'  => '14.287795',
	),
	array(
		'user_id' => '3',
		'name' => 'Oerlikon/Hagenholzstrasse',	
		'country' => 'CH',
		'address' => 'Vegastrasse 2',
		'zipcode' => '8152',
		'city' => 'Zürich',
		'no_latitude'	=> '47.414540',
		'no_longitude'  => '8.559410',
	),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Binz/Grubenstrasse',	  	
	  	'country' => 'CH',
	  	'address' => 'Grubenstrasse 28',
	  	'zipcode' => '8045',
	  	'city' => 'Zürich',
		'no_latitude'	=> '47.361553',
		'no_longitude'  => '8.514373',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Charlottenburg',
	  	'country' => 'DE',
	  	'address' => 'Fürstenbrunner Weg 34',
	  	'zipcode' => '14059',
	  	'city' => 'Berlin',
	  	'no_latitude'	=> '52.522229',
		'no_longitude'  => '13.279800',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Wilmersdorf - Wexstrasse',
	  	'country' => 'DE',
	  	'address' => 'Wexstrasse 40',
	  	'zipcode' => '10715',
	  	'city' => 'Berlin',
	  	'no_latitude'	=> '52.478340',
		'no_longitude'  => '13.333220',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Reinickendorf - Markstrasse',
	  	'country' => 'DE',
	  	'address' => 'Markstrasse 11',
	  	'zipcode' => '13409',
	  	'city' => 'Berlin',
	  	'no_latitude'	=> '52.561820',
		'no_longitude'  => '13.364250',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Friedrichshain - Landsbergerallee',
	  	'country' => 'DE',
	  	'address' => 'Landsberger Allee 63',
	  	'zipcode' => '10249',
	  	'city' => 'Berlin',
	  	'no_latitude'	=> '52.525601',
		'no_longitude'  => '13.444214',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Mariendorf - Lankwitzerstrasse',
	  	'country' => 'DE',
	  	'address' => 'Grossbeerenstrasse 23',
	  	'zipcode' => '12107',
	  	'city' => 'Berlin',
	  	'no_latitude'	=> '52.437000',
		'no_longitude'  => '13.380410',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Zehlendorf - Dahlemer',
	  	'country' => 'DE',
	  	'address' => 'Dahlemer Weg 28/30',
	  	'zipcode' => '14167',
	  	'city' => 'Berlin',
	  	'no_latitude'	=> '52.436950',
		'no_longitude'  => '13.280550',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Mitte - Perleberger',
	  	'country' => 'DE',
	  	'address' => 'Perleberger Strasse',
	  	'zipcode' => '10559',
	  	'city' => 'Berlin',
	  	'no_latitude'	=> '52.532888',
		'no_longitude'  => '13.351252',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Wandsbeck - FED',
	  	'country' => 'DE',
	  	'address' => 'Friedrich Ebert Damm 103',
	  	'zipcode' => '22047',
	  	'city' => 'Hamburg',
	  	'no_latitude'	=> '53.587904',
		'no_longitude'  => '10.089485',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Bramfeld',
	  	'country' => 'DE',
	  	'address' => 'Bramfelder Chaussee 106',
	  	'zipcode' => '22177',
	  	'city' => 'Hamburg',
	  	'no_latitude'	=> '53.600230',
		'no_longitude'  => '10.068100',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Groß Borstel',
	  	'country' => 'DE',
	  	'address' => 'Papenreye 49',
	  	'zipcode' => '22453',
	  	'city' => 'Hamburg',
	  	'no_latitude'	=> '53.613001',
		'no_longitude'  => '9.971004',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Altona',
	  	'country' => 'DE',
	  	'address' => 'Stresemannstrasse 300',
	  	'zipcode' => '22761',
	  	'city' => 'Hamburg',
	  	'no_latitude'	=> '53.563190',
		'no_longitude'  => '9.932580',
		),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Stellingen',
	  	'country' => 'DE',
	  	'address' => 'Kieler Strasse 302',
	  	'zipcode' => '22525',
	  	'city' => 'Hamburg',
	  	'no_latitude'	=> '53.584490',
		'no_longitude'  => '9.933870',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Spalding',
	  	'country' => 'DE',
	  	'address' => 'Spaldingstrasse 72',
	  	'zipcode' => '20097',
	  	'city' => 'Hamburg',
	  	'no_latitude'	=> '53.548730',
		'no_longitude'  => '10.015200',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Harburg',
	  	'country' => 'DE',
	  	'address' => 'Buxtehuderstrasse 75',
	  	'zipcode' => '21073',
	  	'city' => 'Hamburg',
	  	'no_latitude'	=> '53.469275',
		'no_longitude'  => '9.963985',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Bockenheim',
	  	'country' => 'DE',
	  	'address' => 'Ludwig Landmann Strasse 371',
	  	'zipcode' => '60487',
	  	'city' => 'Frankfurt',
	  	'no_latitude'	=> '50.124100',
		'no_longitude'  => '8.622050',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Wiesbaden',
	  	'country' => 'DE',
	  	'address' => 'Mainzerstrasse 79',
	  	'zipcode' => '65189',
	  	'city' => 'Wiesbaden',
	  	'no_latitude'	=> '49.646459',
		'no_longitude'  => '8.361801',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Stuttgart',
	  	'country' => 'DE',
	  	'address' => 'Pragstrasse 130',
	  	'zipcode' => '70376',
	  	'city' => 'Stuttgart',
	  	'no_latitude'	=> '48.807299',
		'no_longitude'  => '9.198625',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Laim',
	  	'country' => 'DE',
	  	'address' => 'Landsbergerstrasse 366',
	  	'zipcode' => '80687',
	  	'city' => 'München',
	  	'no_latitude'	=> '48.144730',
		'no_longitude'  => '11.491550',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Schwabing Nord',
	  	'country' => 'DE',
	  	'address' => 'Frankfurter Ring 6',
	  	'zipcode' => '80807',
	  	'city' => 'München',
	  	'no_latitude'	=> '48.186870',
		'no_longitude'  => '11.568330',
	  ),
	 array(
	  	'user_id' => '3',
	  	'name' => 'Berg am Laim',
	  	'country' => 'DE',
	  	'address' => 'Kreilerstrasse',
	  	'zipcode' => '81673',
	  	'city' => 'München',
	  	'no_latitude'	=> '48.125714',
		'no_longitude'  => '11.647939',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Moosach',
	  	'country' => 'DE',
	  	'address' => 'Dachauerstrasse',
	  	'zipcode' => '80997',
	  	'city' => 'München',
	  	'no_latitude'	=> '48.178196',
		'no_longitude'  => '11.517181',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Schweinau',
	  	'country' => 'DE',
	  	'address' => 'Schweinauer Hauptstrasse 72',
	  	'zipcode' => '90441',
	  	'city' => 'Nürnberg',
	  	'no_latitude'	=> '49.430680',
		'no_longitude'  => '11.044760',
	  ),
	  array(
	  	'user_id' => '3',
	  	'name' => 'Schoppershof',
	  	'country' => 'DE',
	  	'address' => 'Äußere Bayreuther Strasse',
	  	'zipcode' => '90489',
	  	'city' => 'Nürnberg',
	  	'no_latitude'	=> '49.482363',
		'no_longitude'  => '11.117160',
	  ),
	  'deindepotat' => array(
		'user_id'		=> 4,
		'name'          => 'Zissersdorf',		
		'country'       => 'AT',
		'address'       => 'Industriezeile',
		'zipcode'       => '2000',
		'city'          => 'Zissersdorf bei Stockerau',
		'no_latitude'	=> '48.402040',
		'no_longitude'  => '16.140090',
	),
	  'lagerbox1' => array(
		'user_id'		=> 5,
		'name'          => 'LAGERBOX Essen 1',		
		'country'       => 'DE',
		'address'       => 'Hachestraße 50',
		'zipcode'       => '45127',
		'city'          => 'Essen',
		'no_latitude'	=> '51.451760',
		'no_longitude'  => '7.006460',
	),
	  'lagerbox2' => array(
		'user_id'		=> 5,
		'name'          => 'LAGERBOX Düsseldorf 2 - Lierenfeld',		
		'country'       => 'DE',
		'address'       => 'Königsberger Str. 100',
		'zipcode'       => '40231',
		'city'          => 'Düsseldorf',
		'no_latitude'	=> '51.216830',
		'no_longitude'  => '6.829730',
	),
	   'lagerbox3' => array(
		'user_id'		=> 5,
		'name'          => 'LAGERBOX Düsseldorf 1 - Heerdt',		
		'country'       => 'DE',
		'address'       => 'Heerdter Lohweg 226a',
		'zipcode'       => '40549',
		'city'          => 'Düsseldorf',
		'no_latitude'	=> '51.238540',
		'no_longitude'  => '6.728400',
	),
    'lagerbox4' => array(
		'user_id'		=> 5,
		'name'          => 'LAGERBOX BERLIN1-Hohenschönhausen',		
		'country'       => 'DE',
		'address'       => 'Hansastr. 216',
		'zipcode'       => '13051',
		'city'          => 'Berlin',
		'no_latitude'	=> '52.559402',
		'no_longitude'  => '13.494837',
	),
	'lagerbox5' => array(
		'user_id'		=> 5,
		'name'          => 'LAGERBOX BERLIN 2-Neukölln',		
		'country'       => 'DE',
		'address'       => 'Karl-Marx-Str. 92',
		'zipcode'       => '12043',
		'city'          => 'Berlin',
		'no_latitude'	=> '52.480200',
		'no_longitude'  => '13.436190',
	),
	'lagerbox6' => array(
		'user_id'		=> 5,
		'name'          => 'Lagerbox Stuttgart 1 ',		
		'country'       => 'DE',
		'address'       => 'Leobener Str. 73',
		'zipcode'       => '70469',
		'city'          => 'Stuttgart',
		'no_latitude'	=> '48.813995',
		'no_longitude'  => '9.160612',
	),
	'shurgard1' => array(
		'user_id'		=> 8,
		'name'          => 'Paris-Gare de l Est',		
		'country'       => 'FR',
		'address'       => '21-23, rue Eugène Varlin',
		'zipcode'       => '75010',
		'city'          => 'Paris',
		'no_latitude'	=> '48.876141',
		'no_longitude'  => '2.358283',
	),
	'zebrabox1' => array(
		'user_id'		=> 9,
		'name'          => 'Lagerraum Basel - Allschwil',		
		'country'       => 'CH',
		'address'       => 'Lettenweg 118',
		'zipcode'       => '4123',
		'city'          => 'Allschwil',
		'no_latitude'	=> '47.547637',
		'no_longitude'  => '7.551467',
	),
	'zebrabox2' => array(
		'user_id'		=> 9,
		'name'          => 'Lagerraum Bern',		
		'country'       => 'CH',
		'address'       => 'Eigerstrasse 82',
		'zipcode'       => '3007',
		'city'          => 'Bern',
		'no_latitude'	=> '46.939546',
		'no_longitude'  => '7.440839',
	),
	'zebrabox3' => array(
		'user_id'		=> 9,
		'name'          => 'Lagerraum Lausanne',		
		'country'       => 'CH',
		'address'       => 'Rue de Sébeillon 3',
		'zipcode'       => '1004',
		'city'          => 'Lausanne',
		'no_latitude'	=> '46.523244',
		'no_longitude'  => '6.618608',
	),
	'zebrabox4' => array(
		'user_id'		=> 9,
		'name'          => 'Lagerraum Therwil BL',		
		'country'       => 'CH',
		'address'       => 'Oberwilerstrasse 40',
		'zipcode'       => '4106',
		'city'          => 'Therwil',
		'no_latitude'	=> '47.503959',
		'no_longitude'  => '7.554707',
	),
	'zebrabox5' => array(
		'user_id'		=> 9,
		'name'          => 'Lagerraum Zürich - Oerlikon',		
		'country'       => 'CH',
		'address'       => 'Thurgauerstrasse 40',
		'zipcode'       => '8050',
		'city'          => 'Zürich',
		'no_latitude'	=> '47.414736',
		'no_longitude'  => '8.551713',
	),
	'zebrabox6' => array(
		'user_id'		=> 9,
		'name'          => 'Lagerraum Zürich - Schlieren',		
		'country'       => 'CH',
		'address'       => 'Zürcherstrasse 113',
		'zipcode'       => '8952',
		'city'          => 'Schlieren',
		'no_latitude'	=> '47.397916',
		'no_longitude'  => '8.463021',
	),
);

